name: docker-deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ocelot:latest .
          docker tag ocelot:latest ${{ secrets.DOCKER_USERNAME }}/ocelot:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/ocelot:latest

      - name: Deploy to Remote Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/ocelot:latest
            docker stop ocelot || true
            docker rm ocelot || true
            docker run -d --name ocelot -p 8088:8088 ${{ secrets.DOCKER_USERNAME }}/ocelot:latest